---
- name: Create a template from qcow
  hosts: engine
  gather_facts: false

  vars_files:
    - ../vars/{{ password_file }}

  vars:
    qcow_url: file:///root/rhel-server-7.6-x86_64-kvm.qcow2
    image_cache_download: false
    storage_domain: hosted_storage
    template_cluster: Default
    template_name: rhel76_template
    template_memory: 16GiB
    template_cpu: 4
    template_disk_size: 160GiB
    template_disk_storage: hosted_storage

  roles:
    - oVirt.image-template
