apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: >-
      [{"apiVersion":"interconnectedcloud.github.io/v1alpha1","kind":"Qdrouterd","metadata":{"name":"amq-interconnect"},"spec":{"count":2,"deploymentMode": "lbfrontend","image":"quay.io/interconnectedcloud/qdrouterd:1.5.0"}}]
    capabilities: Basic Install
    categories: Messaging
  name: qdrouterd-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - version: v1alpha1
      kind: Qdrouterd
      description: An instance of Qdrouterd
      displayName: Qdrouterd
      name: qdrouterds.interconnectedcloud.github.io
      resources:
      - kind: Service
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: v1
      specDescriptors:
      - description: The desired number of member pods for qdrouterd mesh
        displayName: Count
        path: count
      - description: The deployment mode
        displayName: DeploymentMode
        path: deploymentMode
      - description: The Image
        displayName: Image
        path: image
      - description: Listeners for incoming connections to the router
        displayName: Listeners
        path: listeners
      - description: Listeners for inter router mesh connections
        displayName: InterRouterListeners
        path: interRouterListeners
      - description: TLS/SSL configuration for connections
        displayName: SslProfiles
        path: sslProfiles
      - description: Address configuration for distribution and phasing
        displayName: Addresses
        path: addresses
      statusDescriptors:
      - description: The current revision of the qdrouterd cluster
        displayName: Revision Number
        path: revNumber
      - description: The current pods
        displayName: Pods
        path: pods
      - description: The current conditions
        displayName: Conditions
        path: conditions
  description: |
    The qdrouterd Operator does x y and z
  displayName: Qdrouterd Operator
  install:
    spec:
      deployments:
      - name: qdrouterd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: qdrouterd-operator
          template:
            metadata:
              labels:
                name: qdrouterd-operator
            spec:
              serviceAccountName: qdrouterd-operator
              containers:
              - command:
                - qdrouterd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: qdrouterd-operator
                image: quay.io/interconnectedcloud/qdrouterd-operator
                imagePullPolicy: Always
                name: qdrouterd-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - serviceaccounts
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - "rbac.authorization.k8s.io"
          resources:
          - rolebindings
          - roles
          verbs:
          - get
          - list
          - watch
          - create
          - delete
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - interconnectedcloud.github.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: qdrouterd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.0
