---
- name: Set SA telemetry project
  oc_project:
    state: present
    name: "{{ sa_telemetry_namespace }}"
    node_selector: "{{ sa_telemetry_nodeselector | default(null) }}"

- include_role:
    name: sa_telemetry_prometheus_operator
  vars:
    sa_telemetry_prometheus_operator_namespace: "{{ sa_telemetry_namespace }}"

- include_role:
    name: sa_telemetry_grafana
  vars:
    sa_telemetry_grafana_namespace: "{{ sa_telemetry_namespace }}"

- include_role:
    name: sa_telemetry_prometheus
  vars:
    sa_telemetry_prometheus_namespace: "{{ sa_telemetry_namespace }}"

- include_role:
    name: sa_telemetry_consumers
  vars:
    sa_telemetry_consumers_namespace: "{{ sa_telemetry_namespace }}"

- include_role:
    name: sa_telemetry_qdr
  vars:
    sa_telemetry_qdr_namespace: "{{ sa_telemetry_namespace }}"

- include_role:
    name: sa_telemetry_alertmanager
  vars:
    sa_telemetry_alertmanager_namespace: "{{ sa_telemetry_namespace }}"
