apiVersion: smartgateway.infra.watch/v1alpha1
kind: SmartGateway
metadata:
  name: white
spec:
  size: 1
  amqpmetric_url: qdr-white-normal.sa-telemetry.svc.cluster.local:5672/collectd/telemetry
  debug: "false"
# vim: set tabstop=2 shiftwidth=2 expandtab smartindent:
